_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 47a6add8-c2d2-45d7-8159-ce1f96af9314
name: 'Management Employee Portal'
mail: admin@example.com
slogan: ''
page:
  403: /node/3
  404: /node/4
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
